version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: nishantt95/reverse-proxy 
  backend_user:
    build:
      context: ../../user-service
    image: nishantt95/rest-user
  backend_feed:
    build:
      context: ../../feed-service
    image: nishantt95/rest-feed
  frontend:
    build:
      context: ../../frontend
    image: nishantt95/frontend
