version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: nishantt95/reverse-proxy 
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: nishantt95/rest-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: nishantt95/rest-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: nishantt95/frontend
